function Aij = A22(M,m1F,m2F,m1T,m2T)
%A22
%    AIJ = A22(M,M1F,M2F,M1T,M2T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 15:31:18

Aij = M+m1F+m2F+m1T+m2T;
