function Aij = A51(L2F,ksiF,ksiT,l1,l2,l3,l4,l5,l6,l2F,l2T,l2Tx,m2F,m2T,psiF,psiK)
%A51
%    AIJ = A51(L2F,KSIF,KSIT,L1,L2,L3,L4,L5,L6,L2F,L2T,L2TX,M2F,M2T,PSIF,PSIK)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 15:31:22

t2 = cos(psiF);
t3 = cos(psiK);
t4 = sin(psiK);
t5 = l1.^2;
t6 = l2.^2;
t7 = l3.^2;
t8 = l4.^2;
t10 = 1.0./l1;
t12 = pi./2.0;
t9 = l4.*t3;
t15 = -t12;
t18 = t5./2.0;
t19 = t6./2.0;
t20 = t7./2.0;
t21 = t8./2.0;
t22 = l4.*t4.*1i;
t11 = l3.*t9;
t14 = -t9;
t23 = -t19;
t13 = t11.*2.0;
t16 = -t11;
t25 = l3+t14+t22;
t17 = -t13;
t26 = angle(t25);
t28 = t16+t18+t20+t21+t23;
t24 = t7+t8+t17;
t27 = 1.0./sqrt(t24);
t29 = t10.*t27.*t28;
t30 = acos(t29);
t31 = ksiF+ksiT+psiF+t26+t30;
Aij = m2T.*(sin(ksiF+psiF+t15+t26+t30).*(l1-l5).*2.0+sin(ksiF+psiF+t15).*(l3-l6).*2.0-L2F.*t2.*2.0-l2T.*cos(t31).*2.0+l2Tx.*sin(t31).*2.0+(sin(ksiF+psiF+t12+t26).*2.0)./t27).*(-1.0./2.0)+l2F.*m2F.*t2;
