function Bgi = Bg1(M,alfa,alfaP,g,m1F,m2F,m1T,m2T)
%BG1
%    BGI = BG1(M,ALFA,ALFAP,G,M1F,M2F,M1T,M2T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Nov-2023 11:55:26

t2 = sin(alfa);
t3 = sin(alfaP);
Bgi = -g.*(M.*t2+m1F.*t2+m2F.*t2+m1T.*t2+m2T.*t2)+g.*(M.*t3+m1F.*t3+m2F.*t3+m1T.*t3+m2T.*t3);
