function DDpsT_DpsKDpsF = DDpsT_DpsKDpsF
%DDPST_DPSKDPSF
%    DDPST_DPSKDPSF = DDPST_DPSKDPSF

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Mar-2023 17:01:12

DDpsT_DpsKDpsF = 0.0;
