function DDpsT_DDpsF = DDpsT_DDpsF
%DDPST_DDPSF
%    DDPST_DDPSF = DDPST_DDPSF

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 15:31:47

DDpsT_DDpsF = 0.0;
