function DDpsT_DpsFDpsK = DDpsT_DpsFDpsK
%DDPST_DPSFDPSK
%    DDPST_DPSFDPSK = DDPST_DPSFDPSK

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Mar-2023 17:01:12

DDpsT_DpsFDpsK = 0.0;
