function DDthT_DthFDthK = DDthT_DthFDthK
%DDTHT_DTHFDTHK
%    DDTHT_DTHFDTHK = DDTHT_DTHFDTHK

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Mar-2023 17:01:12

DDthT_DthFDthK = 0.0;
