function DDthT_DDthF = DDthT_DDthF
%DDTHT_DDTHF
%    DDTHT_DDTHF = DDTHT_DDTHF

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 15:31:47

DDthT_DDthF = 0.0;
