function DDthT_DthKDthF = DDthT_DthKDthF
%DDTHT_DTHKDTHF
%    DDTHT_DTHKDTHF = DDTHT_DTHKDTHF

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Mar-2023 17:01:12

DDthT_DthKDthF = 0.0;
