function dpsiFB_dthFB = dpsiFB_dthFB(a,b,f,g,thFB)
%DPSIFB_DTHFB
%    DPSIFB_DTHFB = DPSIFB_DTHFB(A,B,F,G,THFB)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Nov-2023 12:42:11

t2 = cos(thFB);
t3 = sin(thFB);
t4 = a.^2;
t5 = b.^2;
t6 = f.^2;
t7 = g.^2;
t8 = t3.^2;
t9 = a.*t2;
t10 = a.*b.*t3.*2.0;
t11 = -t6;
t21 = t2.*t3.*t4.*t5.*8.0;
t12 = -t9;
t13 = g.*t9.*2.0;
t14 = -t10;
t20 = t4.*t5.*t8.*4.0;
t15 = -t13;
t16 = g+t12;
t17 = t16.^2;
t18 = b.*t16.*2.0;
t23 = a.*t3.*t5.*t16.*8.0;
t24 = t4+t5+t7+t11+t15;
t19 = -t18;
t22 = t5.*t17.*4.0;
t25 = t24.^2;
t27 = a.*g.*t3.*t24.*4.0;
t26 = -t25;
t28 = -t27;
t29 = t20+t22+t26;
t34 = t21+t23+t28;
t30 = sqrt(t29);
t31 = 1.0./t30;
t32 = imag(t30);
t33 = real(t30);
t35 = t14+t33;
t36 = t19+t24+t32;
t38 = t31.*t34;
t37 = t36.^2;
dpsiFB_dthFB = (t37.*((real(t38)./2.0-b.*t9.*2.0)./t36+((t10-t33).*(t14+imag(t38)./2.0+a.*g.*t3.*2.0))./t37).*-2.0)./(t37+(t10-t33).^2);
