function psiFB = psiFB(a,b,f,g,thFB)
%PSIFB
%    PSIFB = PSIFB(A,B,F,G,THFB)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Nov-2023 12:42:11

t2 = cos(thFB);
t3 = sin(thFB);
t4 = a.^2;
t5 = b.^2;
t6 = f.^2;
t7 = g.^2;
t8 = a.*t2;
t9 = -t6;
t10 = -t8;
t11 = g.*t8.*2.0;
t12 = -t11;
t13 = g+t10;
psiFB = atan2(-sqrt(-(t4+t5+t7+t9+t12).^2+t5.*t13.^2.*4.0+t3.^2.*t4.*t5.*4.0)+a.*b.*t3.*2.0,t4+t5+t7+t9+t12-b.*t13.*2.0).*2.0;
