function thetaT_d = thetaT_d_calc(l1,l2,l3,l4,thetaK,thetaF_d,thetaK_d)
%THETAT_D_CALC
%    THETAT_D = THETAT_D_CALC(L1,L2,L3,L4,THETAK,THETAF_D,THETAK_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 17:53:57

t2 = cos(thetaK);
t3 = l1.^2;
t4 = l2.^2;
t5 = l3.^2;
t6 = l4.^2;
t7 = l3.*l4.*t2.*2.0;
t8 = -t7;
t9 = t5+t6+t8;
t10 = 1.0./t9;
thetaT_d = thetaF_d-thetaK_d.*(l4.*t10.*(l4-l3.*t2)+(l3.*l4.*1.0./t9.^(3.0./2.0).*sin(thetaK).*1.0./sqrt((t10.*(t3-t4+t9).^2.*(-1.0./4.0))./t3+1.0).*(-t3+t4+t9))./(l1.*2.0));
