function thetaT = thetaT_calc(ksiF,ksiT,l1,l2,l3,l4,thetaF,thetaK)
%THETAT_CALC
%    THETAT = THETAT_CALC(KSIF,KSIT,L1,L2,L3,L4,THETAF,THETAK)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 17:53:57

t2 = cos(thetaK);
t3 = l3.^2;
t4 = l4.^2;
thetaT = ksiF+ksiT+thetaF+atan2(l4.*sin(thetaK),l3-l4.*t2)+acos((1.0./sqrt(t3+t4-l3.*l4.*t2.*2.0).*(t3./2.0+t4./2.0+l1.^2./2.0-l2.^2./2.0-l3.*l4.*t2))./l1);

thetaT=wrapToPi(thetaT);