function xTib2_d = xTib2_d_calc(L2F,ksiF,l1,l2,l3,l4,l5,l6,psiF,psiK,psiF_d,psiK_d,xH_d)
%XTIB2_D_CALC
%    XTIB2_D = XTIB2_D_CALC(L2F,KSIF,L1,L2,L3,L4,L5,L6,PSIF,PSIK,PSIF_D,PSIK_D,XH_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Sep-2023 20:11:53

t2 = cos(psiK);
t3 = sin(psiK);
t4 = l1.^2;
t5 = l2.^2;
t6 = l3.^2;
t7 = l4.^2;
t10 = -l5;
t11 = 1.0./l1;
t8 = l3.*t2;
t9 = l4.*t2;
t13 = -t5;
t14 = l1+t10;
t18 = l4.*t3.*1i;
t12 = l4.*t8.*2.0;
t15 = -t8;
t16 = -t9;
t17 = -t12;
t19 = l4+t15;
t21 = l3+t16+t18;
t20 = t6+t7+t17;
t22 = angle(t21);
t23 = 1.0./t20;
t24 = 1.0./sqrt(t20);
t25 = ksiF+psiF+t22;
t27 = t4+t13+t20;
t26 = cos(t25);
t28 = (t11.*t24.*t27)./2.0;
t29 = acos(t28);
t30 = t25+t29;
t31 = cos(t30);
xTib2_d = xH_d+psiF_d.*(t14.*t31+L2F.*cos(psiF)+cos(ksiF+psiF).*(l3-l6)-t26./t24)-psiK_d.*(t14.*t31.*(l4.*t19.*t23+(l3.*l4.*t3.*t11.*t24.^3.*1.0./sqrt((t23.*t27.^2.*(-1.0./4.0))./t4+1.0).*(-t4+t5+t20))./2.0)-l4.*t19.*t24.*t26+l3.*l4.*t3.*t24.*sin(t25));
