function yTib1 = yTib1_calc(L1F,ksiF,l1,l2,l3,l4,l5,l6,thetaF,thetaK,yH)
%YTIB1_CALC
%    YTIB1 = YTIB1_CALC(L1F,KSIF,L1,L2,L3,L4,L5,L6,THETAF,THETAK,YH)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Sep-2023 20:11:02

t2 = cos(thetaK);
t3 = sin(thetaK);
t4 = l3.^2;
t5 = l4.^2;
t7 = pi./2.0;
t6 = l4.*t2;
t10 = -t7;
t12 = l4.*t3.*1i;
t8 = l3.*t6.*2.0;
t9 = -t6;
t11 = -t8;
t14 = l3+t9+t12;
t13 = t4+t5+t11;
t15 = angle(t14);
yTib1 = yH+sin(ksiF+t10+thetaF).*(l3-l6)-L1F.*cos(thetaF)+sin(ksiF+t10+t15+thetaF+acos((1.0./sqrt(t13).*(t4./2.0+t5./2.0+l3.*t9+l1.^2./2.0-l2.^2./2.0))./l1)).*(l1-l5)+sqrt(t13).*sin(ksiF+t7+t15+thetaF);
