function yTib2 = yTib2_calc(L2F,ksiF,l1,l2,l3,l4,l5,l6,psiF,psiK,yH)
%YTIB2_CALC
%    YTIB2 = YTIB2_CALC(L2F,KSIF,L1,L2,L3,L4,L5,L6,PSIF,PSIK,YH)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Sep-2023 20:11:51

t2 = cos(psiK);
t3 = sin(psiK);
t4 = l3.^2;
t5 = l4.^2;
t7 = pi./2.0;
t6 = l4.*t2;
t10 = -t7;
t12 = l4.*t3.*1i;
t8 = l3.*t6.*2.0;
t9 = -t6;
t11 = -t8;
t14 = l3+t9+t12;
t13 = t4+t5+t11;
t15 = angle(t14);
yTib2 = yH+sin(ksiF+psiF+t10).*(l3-l6)-L2F.*cos(psiF)+sin(ksiF+psiF+t10+t15+acos((1.0./sqrt(t13).*(t4./2.0+t5./2.0+l3.*t9+l1.^2./2.0-l2.^2./2.0))./l1)).*(l1-l5)+sqrt(t13).*sin(ksiF+psiF+t7+t15);
