function Gi = G1(M,alfa,m1F,m2F,m1T,m2T)
%G1
%    GI = G1(M,ALFA,M1F,M2F,M1T,M2T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Mar-2023 15:31:48

Gi = -sin(alfa).*(M+m1F+m2F+m1T+m2T);
